FROM 10.44.20.71:30020/jnlp-agent-alpine:latest

USER root
RUN curl https://repo.huaweicloud.com/helm/v3.6.3/helm-v3.6.3-linux-amd64.tar.gz -o helm-v3.6.3-linux-amd64.tar.gz \
    && tar -xzf helm-v3.6.3-linux-amd64.tar.gz \
    && mv linux-amd64/helm /usr/local/bin/

RUN curl -LO https://dl.k8s.io/release/v1.18.8/bin/linux/amd64/kubectl && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

USER jenkins



