apiVersion: v1
kind: Service
metadata:
  name: ems-gerrit-agent
  namespace: ems-prod
spec:
  selector:
    app: ems-gerrit-agent
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30042