apiVersion: v1
kind: Service
metadata:
  name: pipeline-trigger
  namespace: ems-infra
spec:
  selector:
    app: pipeline-trigger
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30011