FROM 10.44.20.71:30020/agent-dind

USER root
RUN curl https://mirrors.ustc.edu.cn/golang/go1.21.4.linux-amd64.tar.gz -o go1.21.4.linux-amd64.tar.gz \
    && rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.4.linux-amd64.tar.gz
RUN apk add musl-dev && \
    mkdir /lib64 && \
    ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2 && \
    ln -s /usr/lib/libc.so /usr/lib/libresolv.so.2
ENV PATH ${PATH}:/usr/local/go/bin

USER jenkins