pipeline {
    agent {label 'ems-agent-dind'}

    stages {
        stage('checkout') {
            steps {
                checkout scm
                sh 'ls -al'
            }
        }
        stage('Build') {
            steps {
                sh 'cd agent-go && docker build -t 10.44.20.71:30020/agent-go .'
            }
        }
        stage('publish') {
            steps {
                sh 'docker push 10.44.20.71:30020/agent-go'
            }
        }
    }
}