apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-jenkins
  namespace: ems-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems-jenkins-server
  template:
    metadata:
      labels:
        app: ems-jenkins-server
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: jenkins-admin
      containers:
        - name: ems-jenkins
          image: jenkins/jenkins:2.411
          env:
            - name: JENKINS_OPTS
              value: --prefix=/ems-jenkins
          resources:
            limits:
              memory: "4Gi"
              cpu: "2000m"
            requests:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/ems-jenkins/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/ems-jenkins/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: ems-jenkins-pv-claim