apiVersion: v1
kind: Service
metadata:
  name: ems-jenkins-service
  namespace: ems-infra
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector:
    app: ems-jenkins-server
  type: NodePort
  ports:
    - name: httpport
      port: 8080
      targetPort: 8080
      nodePort: 30010
    - name: jnlpport
      port: 50000
      targetPort: 50000