---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ems-jenkins-pv
  labels:
    app: ems-jenkins
spec:
  storageClassName: slow
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: ems-jenkins-pv-claim
    namespace: ems-infra
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/nfs_data/ems-jenkins
    server: 10.44.20.75
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ems-jenkins-pv-claim
  namespace: ems-infra
spec:
  storageClassName: slow
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi