pipeline {
    agent  { label 'ems-agent-go' }

    stages {
        stage('Clone') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
          steps {
                script {
                    sh '''
                        cd jira-agent
                        go env -w GO111MODULE=on && \
                        go env -w GOPROXY=https://goproxy.cn,direct && \
                        go mod download && \
                        CGO_ENABLED=0 GOOS=linux go build -o jira-agent && \
                        docker build -t 10.44.20.71:30020/jira-agent:latest .
                    '''
                }
            }
        }
        stage('Publish') {
            steps {
                script {
                    sh "docker push 10.44.20.71:30020/jira-agent:latest"
                }
            }
        }
        stage('deploy test') {
            agent {label 'ems-agent-kubernetes'}
            steps {
                sh "kubectl rollout restart deployment ems-jira-agent -n ems-test"
                sh "kubectl rollout status deployment ems-jira-agent -n ems-test -w"
            }
        }
        // stage('Approve based on environment lead') {
        //     agent none
        //     input {
        //         message 'Deploy to prod Env?'
        //         id 'emsApproval'
        //         submitter 'Alice, Bob'
        //         submitterParameter 'approverId'
        //     }

        //     steps {
        //         echo "Deployment approved by ${approverId}."
        //     }
        // }
        // stage('deploy prod') {
        //     agent {label 'ems-agent-kubernetes'}
        //     steps {
        //         sh "kubectl rollout restart deployment ems-jira-agent -n ems-prod"
        //         sh "kubectl rollout status deployment ems-jira-agent -n ems-prod -w"
        //     }
        // }
    }
}