apiVersion: v1
kind: PersistentVolume
metadata: 
  name: es-pv
  namespace: ems-infra
  labels: 
    pv: es-pv
spec: 
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 300Gi
  storageClassName: nfs
  nfs: 
    path: "/data/nfs_data/es-data"
    server: 10.44.20.75
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: es-pvc
  namespace: ems-infra
spec: 
  accessModes: 
    - ReadWriteOnce       
  resources: 
    requests: 
      storage: 300Gi
  storageClassName: nfs 
  selector: 
    matchLabels: 
      pv: es-pv 
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: ems-infra
spec:
  type: NodePort
  ports:
  - name: db
    nodePort: 30092
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: ems-infra
data:
  elasticsearch.yml: |
    discovery.type: single-node
    network.host: 0.0.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: ems-infra
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
      - env:
        image: elasticsearch:7.17.13
        name: elasticsearch
        ports:
        - containerPort: 9200
          name: data
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          limits:
            cpu: 4000m
            memory: 6Gi
          requests:
            cpu: 2000m
            memory: 4Gi
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data/
          name: vol-data
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
          name: es-config
      volumes:
        - name: es-config
          configMap:
            name: es-config
        - name: vol-data
          persistentVolumeClaim:
            claimName: es-pvc
