apiVersion: v1
kind: Service
metadata:
  name: ems-test-database-service
  namespace: ems-test
spec:
  selector:
    app: ems-test-database
  type: NodePort
  ports:
    - name: httpport
      port: 3306
      targetPort: 3306
      nodePort: 30036