ems:
  url: http://ems-test:9010/commits
  pageSize: 10
  interval: 5
lark:
  auth:
    url: https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal
    app_id: <app_id>
    app_secret: <app_secret>
  template:
    app_id: <template_id>
    folder_id: <folder_id>