pipeline {
    agent  {
        label 'ems-agent-go'
    }

    stages {
        stage('Clone') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
          steps {
                script {
                    sh '''
                        cd pipeline-trigger
                        go env -w GO111MODULE=on && \
                        go env -w GOPROXY=https://goproxy.cn,direct && \
                        go mod download && \
                        CGO_ENABLED=0 GOOS=linux go build -o pipeline-trigger && \
                        docker build -t 10.44.20.71:30020/pipeline-trigger:latest .
                    '''
                }
            }
        }
        stage('Publish') {
            steps {
                script {
                    sh "docker push 10.44.20.71:30020/pipeline-trigger:latest"
                }
            }
        }
    }
}