ems:
  url: http://ems:9010/commits
gerrit:
  username: <username>
  password: <password>
es:
  url: http://elasticsearch.ems-infra:9200/gerrit-change-requests
  username: <username>
  password: <password>