apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: ems-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
      - name: registry
        image: registry:2.8.2
        ports:
        - containerPort: 5000
        env:
        # - name: REGISTRY_HTTP_TLS_CERTIFICATE
        #   value: "/certs/tls.crt"
        # - name: REGISTRY_HTTP_TLS_KEY
        #   value: "/certs/tls.key"
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
          subPath: registry
        - name: registry-config
          mountPath: /etc/docker/registry
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: registry-pv-claim
      - name: registry-config
        configMap:
          defaultMode: 420
          name: registry-config
        