---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  labels:
    app: registry
spec:
  storageClassName: slow
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: registry-pv-claim
    namespace: ems-infra
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/nfs_data/docker-registry
    server: 10.44.20.75
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pv-claim
  namespace: ems-infra
spec:
  storageClassName: slow
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi